package schema

// allFields contains field definitions for the remaining LOC-defined MARC21
// bibliographic tags not included in [commonFields]. These are appended when
// [Build] is called with [All] coverage.
//
// Tags are ordered numerically. Less-common tags include at minimum a label
// and definition; frequently-used subfields are included where practical.
//
// Source: https://www.loc.gov/marc/bibliographic/
var allFields = []Field{

	// ── Additional 0XX ───────────────────────────────────────────────────────
	{
		Tag:        "011",
		Label:      "Library of Congress Copy/Version Identification Number",
		Definition: "Identifies a specific copy or version of an item in the LC catalog.",
		Repeatable: false,
		Common:     false,
		Control:    false,
	},
	{
		Tag:        "013",
		Label:      "Patent Control Information",
		Definition: "Information needed to identify a specific patent document and the activities related to the patent.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Number", Repeatable: false},
			{Code: "b", Label: "Country", Repeatable: false},
			{Code: "c", Label: "Type of number", Repeatable: false},
			{Code: "d", Label: "Date", Repeatable: true},
			{Code: "e", Label: "Status", Repeatable: true},
			{Code: "f", Label: "Party to document", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "017",
		Label:      "Copyright or Legal Deposit Number",
		Definition: "A number assigned to the item for copyright or legal deposit purposes.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Copyright or legal deposit number", Repeatable: true},
			{Code: "b", Label: "Assigning agency", Repeatable: false},
			{Code: "d", Label: "Date", Repeatable: false},
			{Code: "i", Label: "Display text", Repeatable: false},
			{Code: "z", Label: "Canceled/invalid copyright or legal deposit number", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "018",
		Label:      "Copyright Article-Fee Code",
		Definition: "Code used to communicate copyright article-fee status.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Copyright article-fee code", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "024",
		Label:      "Other Standard Identifier",
		Definition: "A standard number or code not accommodated by other fields (ISRC, UPC, ISMN, etc.).",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of standard number or code", Values: map[string]string{"0": "International Standard Recording Code (ISRC)", "1": "Universal Product Code (UPC)", "2": "International Standard Music Number (ISMN)", "3": "International Article Number (EAN)", "4": "Serial Item and Contribution Identifier (SICI)", "7": "Source specified in $2", "8": "Unspecified type of standard number or code"}},
			{Label: "Difference indicator", Values: map[string]string{"#": "No information provided", "0": "No difference", "1": "Difference"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Standard number or code", Repeatable: false},
			{Code: "c", Label: "Terms of availability", Repeatable: false},
			{Code: "d", Label: "Additional codes following the standard number or code", Repeatable: false},
			{Code: "q", Label: "Qualifying information", Repeatable: true},
			{Code: "z", Label: "Canceled/invalid standard number or code", Repeatable: true},
			{Code: "2", Label: "Source of number or code", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "025",
		Label:      "Overseas Acquisition Number",
		Definition: "The overseas acquisition number assigned by the Library of Congress.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Overseas acquisition number", Repeatable: true}},
	},
	{
		Tag:        "026",
		Label:      "Fingerprint Identifier",
		Definition: "A fingerprint identifier used to identify early printed books and other pre-modern printed material.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "First and second groups of characters", Repeatable: false},
			{Code: "b", Label: "Third and fourth groups of characters", Repeatable: false},
			{Code: "c", Label: "Date", Repeatable: false},
			{Code: "d", Label: "Number of volume or part", Repeatable: true},
			{Code: "e", Label: "Unparsed fingerprint", Repeatable: false},
			{Code: "2", Label: "Source", Repeatable: false},
			{Code: "5", Label: "Institution to which field applies", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "027",
		Label:      "Standard Technical Report Number",
		Definition: "A report number assigned to a technical report according to ANSI/NISO Z39.23.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Standard technical report number", Repeatable: false},
			{Code: "q", Label: "Qualifying information", Repeatable: true},
			{Code: "z", Label: "Canceled/invalid number", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "028",
		Label:      "Publisher or Distributor Number",
		Definition: "A formatted number used to identify a sound recording, videorecording, or notated music publication.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of number", Values: map[string]string{"0": "Issue number", "1": "Matrix number", "2": "Plate number", "3": "Other music number", "4": "Videorecording number", "5": "Other publisher number"}},
			{Label: "Note/added entry controller", Values: map[string]string{"0": "No note, no added entry", "1": "Note, added entry", "2": "Note, no added entry", "3": "No note, added entry"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Publisher or distributor number", Repeatable: false},
			{Code: "b", Label: "Source", Repeatable: false},
			{Code: "q", Label: "Qualifying information", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "030",
		Label:      "CODEN Designation",
		Definition: "The CODEN for the serial.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "CODEN", Repeatable: false}, {Code: "z", Label: "Canceled/invalid CODEN", Repeatable: true}, sfLink, sfFieldLink},
	},
	{
		Tag:        "031",
		Label:      "Musical Incipits Information",
		Definition: "Information about a musical incipit (the beginning notes of a musical composition).",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Number of work", Repeatable: false},
			{Code: "b", Label: "Number of movement", Repeatable: false},
			{Code: "c", Label: "Number of excerpt", Repeatable: false},
			{Code: "d", Label: "Caption or heading", Repeatable: true},
			{Code: "e", Label: "Role", Repeatable: false},
			{Code: "g", Label: "Clef", Repeatable: false},
			{Code: "m", Label: "Voice/instrument", Repeatable: false},
			{Code: "n", Label: "Key signature", Repeatable: false},
			{Code: "o", Label: "Time signature", Repeatable: false},
			{Code: "p", Label: "Musical notation", Repeatable: false},
			{Code: "q", Label: "General note", Repeatable: true},
			{Code: "r", Label: "Key or mode", Repeatable: false},
			{Code: "s", Label: "Coded validity note", Repeatable: true},
			{Code: "t", Label: "Text incipit", Repeatable: true},
			{Code: "u", Label: "Uniform Resource Identifier", Repeatable: true},
			{Code: "y", Label: "Link text", Repeatable: true},
			{Code: "z", Label: "Public note", Repeatable: true},
			{Code: "2", Label: "System code", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "032",
		Label:      "Postal Registration Number",
		Definition: "The number assigned by the US Postal Service to a serial publication.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Postal registration number", Repeatable: false}, {Code: "b", Label: "Source agency assigning number", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "033",
		Label:      "Date/Time and Place of an Event",
		Definition: "Formatted data about the date, time, and place when a captured event occurred.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of date in $a", Values: map[string]string{"#": "No date information", "0": "Single date", "1": "Multiple single dates", "2": "Range of dates"}},
			{Label: "Type of event", Values: map[string]string{"#": "No information provided", "0": "Capture", "1": "Broadcast", "2": "Finding"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Formatted date/time", Repeatable: true},
			{Code: "b", Label: "Geographic classification area code", Repeatable: true},
			{Code: "c", Label: "Geographic classification subarea code", Repeatable: true},
			{Code: "p", Label: "Place of event", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "2", Label: "Source of term", Repeatable: true},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "034",
		Label:      "Coded Cartographic Mathematical Data",
		Definition: "Mathematically coded representations of geographic features: scale, projection, etc.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of scale", Values: map[string]string{"0": "Scale indeterminable/No scale recorded", "1": "Single scale", "3": "Range of scales"}},
			{Label: "Type of ring", Values: map[string]string{"#": "Not applicable", "0": "Outer ring", "1": "Exclusion ring"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Category of scale", Repeatable: false},
			{Code: "b", Label: "Constant ratio linear horizontal scale", Repeatable: true},
			{Code: "c", Label: "Constant ratio linear vertical scale", Repeatable: true},
			{Code: "d", Label: "Coordinates—westernmost longitude", Repeatable: false},
			{Code: "e", Label: "Coordinates—easternmost longitude", Repeatable: false},
			{Code: "f", Label: "Coordinates—northernmost latitude", Repeatable: false},
			{Code: "g", Label: "Coordinates—southernmost latitude", Repeatable: false},
			{Code: "p", Label: "Equinox", Repeatable: false},
			{Code: "r", Label: "Distance from earth", Repeatable: false},
			{Code: "s", Label: "G-ring latitude", Repeatable: true},
			{Code: "t", Label: "G-ring longitude", Repeatable: true},
			{Code: "x", Label: "Beginning date", Repeatable: false},
			{Code: "y", Label: "Ending date", Repeatable: false},
			{Code: "z", Label: "Name of extraterrestrial body", Repeatable: false},
			{Code: "2", Label: "Source", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "036",
		Label:      "Original Study Number for Computer Data Files",
		Definition: "The original study number that is assigned to a computer file by the producer of the file.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Original study number", Repeatable: false}, {Code: "b", Label: "Source agency assigning number", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "037",
		Label:      "Source of Acquisition",
		Definition: "The source from which the item may be obtained.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Source of acquisition sequence", Values: map[string]string{"#": "Not applicable/No information provided/Earliest", "2": "Intervening", "3": "Current/latest"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Stock number", Repeatable: false},
			{Code: "b", Label: "Source of stock number/acquisition", Repeatable: false},
			{Code: "c", Label: "Terms of availability", Repeatable: true},
			{Code: "f", Label: "Form of issue", Repeatable: true},
			{Code: "g", Label: "Additional format characteristics", Repeatable: true},
			{Code: "n", Label: "Note", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "038",
		Label:      "Record Content Licensor",
		Definition: "Contains the MARC organization code of the agency authorizing use of the record.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Record content licensor", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "042",
		Label:      "Authentication Code",
		Definition: "A code indicating that the record has been authenticated by an agency and the standard that the agency used.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Authentication code", Repeatable: true}},
	},
	{
		Tag:        "044",
		Label:      "Country of Publishing/Producing Entity Code",
		Definition: "MARC code(s) for the country associated with the publishing or producing entity.",
		Repeatable: false,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "MARC country code", Repeatable: true},
			{Code: "b", Label: "Local subentity code", Repeatable: true},
			{Code: "c", Label: "ISO country code", Repeatable: true},
			{Code: "2", Label: "Source of local subentity code", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "045",
		Label:      "Time Period of Content",
		Definition: "Time period(s) covered by the content of the item.",
		Repeatable: false,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of time period in $b or $c", Values: map[string]string{"#": "Subfield $b or $c not present", "0": "Single date/time", "1": "Multiple single dates/times", "2": "Range of dates/times"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Time period code", Repeatable: true},
			{Code: "b", Label: "Formatted 9999 BC through 9999 AD date", Repeatable: true},
			{Code: "c", Label: "Formatted pre-9999 BC date", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "046",
		Label:      "Special Coded Dates",
		Definition: "Formatted dates associated with an item, such as the date the item was created, revised, issued, or withdrawn.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Type of date code", Repeatable: false},
			{Code: "b", Label: "Date 1, BC date", Repeatable: false},
			{Code: "c", Label: "Date 1, CE date", Repeatable: false},
			{Code: "d", Label: "Date 2, BC date", Repeatable: false},
			{Code: "e", Label: "Date 2, CE date", Repeatable: false},
			{Code: "j", Label: "Date resource modified", Repeatable: false},
			{Code: "k", Label: "Beginning or single date created", Repeatable: false},
			{Code: "l", Label: "Ending date created", Repeatable: false},
			{Code: "m", Label: "Beginning of date valid", Repeatable: false},
			{Code: "n", Label: "End of date valid", Repeatable: false},
			{Code: "o", Label: "Single or starting date for aggregated content", Repeatable: false},
			{Code: "p", Label: "Ending date for aggregated content", Repeatable: false},
			{Code: "2", Label: "Source of date", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "047",
		Label:      "Form of Musical Composition Code",
		Definition: "A code that indicates the form of musical composition.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "First indicator", Values: map[string]string{"#": "Undefined"}},
			{Label: "Source of code", Values: map[string]string{"#": "MARC musical composition code", "7": "Source specified in $2"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Form of musical composition code", Repeatable: true},
			{Code: "2", Label: "Source of code", Repeatable: false},
		},
	},
	{
		Tag:        "048",
		Label:      "Number of Musical Instruments or Voices Code",
		Definition: "Coded information about the medium of performance of a musical composition.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "First indicator", Values: map[string]string{"#": "Undefined"}},
			{Label: "Source of code", Values: map[string]string{"#": "MARC code", "7": "Source specified in $2"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Performer or ensemble", Repeatable: true},
			{Code: "b", Label: "Soloist", Repeatable: true},
			{Code: "2", Label: "Source of code", Repeatable: false},
		},
	},
	{
		Tag:        "051",
		Label:      "Library of Congress Copy and Version Identification",
		Definition: "Copy or version information for items in the LC collections.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Classification number", Repeatable: false},
			{Code: "b", Label: "Item number", Repeatable: false},
			{Code: "c", Label: "Copy information", Repeatable: false},
		},
	},
	{
		Tag:        "052",
		Label:      "Geographic Classification",
		Definition: "Geographic classification codes from the LC Geographic Classification.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Code source", Values: map[string]string{"#": "Library of Congress Classification", "1": "U.S. Dept. of Defense Classification", "7": "Source specified in $2"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Geographic classification area code", Repeatable: false},
			{Code: "b", Label: "Geographic classification subarea code", Repeatable: true},
			{Code: "d", Label: "Populated place name", Repeatable: true},
			{Code: "2", Label: "Code source", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "055",
		Label:      "Classification Numbers Assigned in Canada",
		Definition: "Classification numbers assigned by Library and Archives Canada or the National Library of Canada.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Classification number", Repeatable: false},
			{Code: "b", Label: "Item number", Repeatable: false},
			{Code: "2", Label: "Source of classification number", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "060",
		Label:      "National Library of Medicine Call Number",
		Definition: "The National Library of Medicine (NLM) classification number and item number assigned to the item.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Classification number", Repeatable: true},
			{Code: "b", Label: "Item number", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "061",
		Label:      "National Library of Medicine Copy Statement",
		Definition: "Copy-specific information for NLM holdings.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Classification number", Repeatable: true}, {Code: "b", Label: "Item number", Repeatable: false}, {Code: "c", Label: "Copy information", Repeatable: false}},
	},
	{
		Tag:        "066",
		Label:      "Character Sets Present",
		Definition: "The character sets present in the record.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Primary G0 character set", Repeatable: false}, {Code: "b", Label: "Primary G1 character set", Repeatable: false}, {Code: "c", Label: "Alternate G0 or G1 character set", Repeatable: true}},
	},
	{
		Tag:        "070",
		Label:      "National Agricultural Library Call Number",
		Definition: "The classification number assigned by the National Agricultural Library.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Classification number", Repeatable: true}, {Code: "b", Label: "Item number", Repeatable: false}, sfFieldLink},
	},
	{
		Tag:        "071",
		Label:      "National Agricultural Library Copy Statement",
		Definition: "Copy-specific information for NAL holdings.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Classification number", Repeatable: true}, {Code: "b", Label: "Item number", Repeatable: false}, {Code: "c", Label: "Copy information", Repeatable: false}},
	},
	{
		Tag:        "072",
		Label:      "Subject Category Code",
		Definition: "A subject category code from a specific subject category code list.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "First indicator", Values: map[string]string{"#": "Undefined"}},
			{Label: "Code source", Values: map[string]string{"0": "NAL subject category code list", "7": "Source specified in $2"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Subject category code", Repeatable: false},
			{Code: "x", Label: "Subject category code subdivision", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "074",
		Label:      "GPO Item Number",
		Definition: "The item number assigned by the US Government Publishing Office (GPO) to a publication.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "GPO item number", Repeatable: false}, {Code: "z", Label: "Canceled/invalid GPO item number", Repeatable: true}, sfFieldLink},
	},
	{
		Tag:        "080",
		Label:      "Universal Decimal Classification Number",
		Definition: "A Universal Decimal Classification (UDC) number assigned to the item.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of edition", Values: map[string]string{"#": "No information provided", "0": "Full", "1": "Abridged"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Universal Decimal Classification number", Repeatable: false},
			{Code: "b", Label: "Item number", Repeatable: false},
			{Code: "x", Label: "Common auxiliary subdivision", Repeatable: true},
			{Code: "2", Label: "Edition identifier", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "083",
		Label:      "Additional Dewey Decimal Classification Number",
		Definition: "An additional Dewey Decimal Classification number assigned to an item.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Classification number", Repeatable: true},
			{Code: "c", Label: "Classification number—ending number of span", Repeatable: true},
			{Code: "q", Label: "Assigning agency", Repeatable: false},
			{Code: "y", Label: "Table sequence number for internal subarrangement or add table", Repeatable: true},
			{Code: "z", Label: "Table identification", Repeatable: true},
			{Code: "2", Label: "Edition number", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "084",
		Label:      "Other Classification Number",
		Definition: "A classification number from a classification scheme other than those covered by specific fields.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Classification number", Repeatable: true},
			{Code: "b", Label: "Item number", Repeatable: false},
			{Code: "q", Label: "Assigning agency", Repeatable: false},
			{Code: "2", Label: "Source of number", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "085",
		Label:      "Synthesized Classification Number Components",
		Definition: "Identifies the components of a classification number that was synthesized by adding facets, subdivisions, etc.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Number where instructions are found—single number or beginning number of span", Repeatable: true},
			{Code: "b", Label: "Base number", Repeatable: true},
			{Code: "c", Label: "Classification number—ending number of span", Repeatable: true},
			{Code: "f", Label: "Facet designator", Repeatable: true},
			{Code: "r", Label: "Root number", Repeatable: true},
			{Code: "s", Label: "Digits added from classification number in schedule or external table", Repeatable: true},
			{Code: "t", Label: "Digits added from internal subarrangement or add table", Repeatable: true},
			{Code: "u", Label: "Number being analyzed", Repeatable: true},
			{Code: "v", Label: "Number in internal subarrangement or add table where instructions are found", Repeatable: true},
			{Code: "w", Label: "Table identification—Internal subarrangement or add table", Repeatable: true},
			{Code: "y", Label: "Table sequence number for internal subarrangement or add table", Repeatable: true},
			{Code: "z", Label: "Table identification", Repeatable: true},
			{Code: "6", Label: "Linkage", Repeatable: false},
			sfFieldLink,
		},
	},
	{
		Tag:        "088",
		Label:      "Report Number",
		Definition: "A report number assigned to the item being cataloged.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Report number", Repeatable: false},
			{Code: "z", Label: "Canceled/invalid report number", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},

	// ── Additional 2XX ───────────────────────────────────────────────────────
	{
		Tag:        "242",
		Label:      "Translation of Title by Cataloging Agency",
		Definition: "A translation of the title proper (field 245) by the cataloging agency when the translated title is not given in another field.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Title added entry", Values: map[string]string{"0": "No added entry", "1": "Added entry"}},
			{Label: "Nonfiling characters", Values: map[string]string{"0": "No nonfiling characters", "1": "1 nonfiling character", "2": "2 nonfiling characters", "3": "3 nonfiling characters", "4": "4 nonfiling characters", "5": "5 nonfiling characters", "6": "6 nonfiling characters", "7": "7 nonfiling characters", "8": "8 nonfiling characters", "9": "9 nonfiling characters"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Title", Repeatable: false},
			{Code: "b", Label: "Remainder of title", Repeatable: false},
			{Code: "c", Label: "Statement of responsibility, etc.", Repeatable: false},
			{Code: "n", Label: "Number of part/section of a work", Repeatable: true},
			{Code: "p", Label: "Name of part/section of a work", Repeatable: true},
			{Code: "y", Label: "Language code of translated title", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "243",
		Label:      "Collective Uniform Title",
		Definition: "The collective uniform title for a group of works, used only when the main entry is under a personal, corporate, or meeting name.",
		Repeatable: false,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Uniform title", Repeatable: false},
			{Code: "d", Label: "Date of treaty signing", Repeatable: true},
			{Code: "f", Label: "Date of a work", Repeatable: false},
			{Code: "g", Label: "Miscellaneous information", Repeatable: true},
			{Code: "h", Label: "Medium", Repeatable: false},
			{Code: "k", Label: "Form subheading", Repeatable: true},
			{Code: "l", Label: "Language of a work", Repeatable: false},
			{Code: "m", Label: "Medium of performance for music", Repeatable: true},
			{Code: "n", Label: "Number of part/section of a work", Repeatable: true},
			{Code: "o", Label: "Arrangement of music", Repeatable: false},
			{Code: "p", Label: "Name of part/section of a work", Repeatable: true},
			{Code: "r", Label: "Key for music", Repeatable: false},
			{Code: "s", Label: "Version", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},

	// ── Additional 3XX ───────────────────────────────────────────────────────
	{
		Tag:        "306",
		Label:      "Playing Time",
		Definition: "The playing time of a sound recording, videorecording, etc.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Playing time", Repeatable: true}, sfLink, sfFieldLink},
	},
	{
		Tag:        "307",
		Label:      "Hours, Etc.",
		Definition: "Hours during which a location or service is available.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Hours", Repeatable: false}, {Code: "b", Label: "Additional information", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "340",
		Label:      "Medium",
		Definition: "The physical medium on which or in which the item is carried.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Material base and configuration", Repeatable: true},
			{Code: "b", Label: "Dimensions", Repeatable: true},
			{Code: "c", Label: "Materials applied to surface", Repeatable: true},
			{Code: "d", Label: "Information recording technique", Repeatable: true},
			{Code: "e", Label: "Support", Repeatable: true},
			{Code: "f", Label: "Production rate/ratio", Repeatable: true},
			{Code: "g", Label: "Color content", Repeatable: true},
			{Code: "h", Label: "Location within medium", Repeatable: true},
			{Code: "i", Label: "Technical specifications of medium", Repeatable: true},
			{Code: "j", Label: "Generation", Repeatable: true},
			{Code: "k", Label: "Layout", Repeatable: true},
			{Code: "l", Label: "Font size", Repeatable: true},
			{Code: "m", Label: "Book format", Repeatable: true},
			{Code: "n", Label: "Polarity", Repeatable: true},
			{Code: "o", Label: "Regional encoding", Repeatable: true},
			{Code: "p", Label: "Illustrative content", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "380",
		Label:      "Form of Work",
		Definition: "A class or genre to which a work belongs.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Form of work", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source of term", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "381",
		Label:      "Other Distinguishing Characteristics of Work or Expression",
		Definition: "Other characteristics that serve to differentiate a work or expression from another work or expression with the same title.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Other distinguishing characteristic", Repeatable: true},
			{Code: "u", Label: "Uniform Resource Identifier", Repeatable: true},
			{Code: "v", Label: "Source of information", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source of term", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "382",
		Label:      "Medium of Performance",
		Definition: "The medium of performance for a musical work or expression.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Medium of performance", Repeatable: true},
			{Code: "b", Label: "Soloist", Repeatable: true},
			{Code: "d", Label: "Doubling instrument", Repeatable: true},
			{Code: "e", Label: "Number of ensembles of the same type", Repeatable: true},
			{Code: "n", Label: "Number of performers of the same medium", Repeatable: true},
			{Code: "p", Label: "Alternative medium of performance", Repeatable: true},
			{Code: "r", Label: "Total number of individuals performing alongside ensemble", Repeatable: false},
			{Code: "s", Label: "Total number of performers", Repeatable: false},
			{Code: "t", Label: "Total number of ensembles", Repeatable: false},
			{Code: "v", Label: "Note", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source of term", Repeatable: false},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "383",
		Label:      "Numeric Designation of Musical Work",
		Definition: "Numeric designation(s) of a musical work, including opus, serial number, and thematic index number.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Serial number", Repeatable: true},
			{Code: "b", Label: "Opus number", Repeatable: true},
			{Code: "c", Label: "Thematic index number", Repeatable: true},
			{Code: "d", Label: "Thematic index code", Repeatable: false},
			{Code: "e", Label: "Publisher associated with opus number", Repeatable: false},
			{Code: "2", Label: "Source", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "384",
		Label:      "Key",
		Definition: "The key in which a musical work is written.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Key", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "385",
		Label:      "Audience Characteristics",
		Definition: "A term that describes the characteristics of the intended audience.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Audience term", Repeatable: true},
			{Code: "b", Label: "Audience code", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "386",
		Label:      "Creator/Contributor Characteristics",
		Definition: "A term that describes the characteristics of the creator or contributor of a work.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Creator/contributor term", Repeatable: true},
			{Code: "b", Label: "Creator/contributor code", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "388",
		Label:      "Time Period of Creation",
		Definition: "A time period associated with the creation of a work or expression.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of time period", Values: map[string]string{"#": "No information provided", "1": "Creation of work", "2": "Creation of aggregate work"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Time period of creation term", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "1", Label: "Real World Object URI", Repeatable: true},
			{Code: "2", Label: "Source of term", Repeatable: false},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},

	// ── Additional 5XX Notes ─────────────────────────────────────────────────
	{
		Tag:        "588",
		Label:      "Source of Description Note",
		Definition: "A note that identifies the latest issue consulted, and the basis for the description of the item.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Display constant controller", Values: map[string]string{"#": "No information provided", "0": "Source of description", "1": "Latest issue consulted"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{{Code: "a", Label: "Source of description note", Repeatable: false}, {Code: "5", Label: "Institution to which field applies", Repeatable: false}, sfLink, sfFieldLink},
	},

	// ── Additional 6XX ───────────────────────────────────────────────────────

	// ── Additional 7XX ───────────────────────────────────────────────────────

	// ── 841-887 — Holdings, Alternate Graphics, etc. ─────────────────────────
	{
		Tag:        "841",
		Label:      "Holdings Coded Data Values",
		Definition: "Coded information for holdings records. Provides leader/008-equivalent information for MARC holdings records.",
		Repeatable: false,
		Common:     false,
	},
	{
		Tag:        "842",
		Label:      "Textual Physical Form Designator",
		Definition: "The physical form designator of the item.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Textual physical form designator", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "843",
		Label:      "Reproduction Note",
		Definition: "A note about a reproduction of the described item when the record is for the original.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Type of reproduction", Repeatable: false},
			{Code: "b", Label: "Place of reproduction", Repeatable: true},
			{Code: "c", Label: "Agency responsible for reproduction", Repeatable: true},
			{Code: "d", Label: "Date of reproduction", Repeatable: false},
			{Code: "e", Label: "Physical description of reproduction", Repeatable: false},
			{Code: "f", Label: "Series statement of reproduction", Repeatable: true},
			{Code: "m", Label: "Dates and/or sequential designations of issues reproduced", Repeatable: true},
			{Code: "n", Label: "Note about reproduction", Repeatable: true},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			{Code: "5", Label: "Institution to which field applies", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "844",
		Label:      "Name of Unit",
		Definition: "The name of the unit at the location given in field 852.",
		Repeatable: false,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Name of unit", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "845",
		Label:      "Terms Governing Use and Reproduction Note",
		Definition: "Terms governing use and reproduction of the material.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Terms governing use and reproduction", Repeatable: false},
			{Code: "b", Label: "Jurisdiction", Repeatable: false},
			{Code: "c", Label: "Authorization", Repeatable: false},
			{Code: "d", Label: "Authorized users", Repeatable: false},
			{Code: "u", Label: "Uniform Resource Identifier", Repeatable: true},
			{Code: "3", Label: "Materials specified", Repeatable: false},
			{Code: "5", Label: "Institution to which field applies", Repeatable: false},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "850",
		Label:      "Holding Institution",
		Definition: "The MARC organization code of the institution that holds the item described.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Holding institution", Repeatable: true}, sfFieldLink},
	},
	{
		Tag:        "853",
		Label:      "Captions and Pattern–Basic Bibliographic Unit",
		Definition: "Captions and a pattern for the holdings of the basic bibliographic unit.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "854",
		Label:      "Captions and Pattern–Supplementary Material",
		Definition: "Captions and a pattern for supplementary material holdings.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "855",
		Label:      "Captions and Pattern–Indexes",
		Definition: "Captions and a pattern for index holdings.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "863",
		Label:      "Enumeration and Chronology–Basic Bibliographic Unit",
		Definition: "Enumeration and chronology data for the holdings of the basic bibliographic unit.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "864",
		Label:      "Enumeration and Chronology–Supplementary Material",
		Definition: "Enumeration and chronology data for supplementary material holdings.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "865",
		Label:      "Enumeration and Chronology–Indexes",
		Definition: "Enumeration and chronology data for index holdings.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "866",
		Label:      "Textual Holdings–Basic Bibliographic Unit",
		Definition: "Free-text summary holdings statements for the basic bibliographic unit.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Textual holdings", Repeatable: false}, {Code: "z", Label: "Public note", Repeatable: true}, {Code: "2", Label: "Source of notation", Repeatable: false}, sfLink, sfFieldLink},
	},
	{
		Tag:        "867",
		Label:      "Textual Holdings–Supplementary Material",
		Definition: "Free-text summary holdings statements for supplementary material.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Textual holdings", Repeatable: false}, {Code: "z", Label: "Public note", Repeatable: true}},
	},
	{
		Tag:        "868",
		Label:      "Textual Holdings–Indexes",
		Definition: "Free-text summary holdings statements for indexes.",
		Repeatable: true,
		Common:     false,
		Subfields:  []Subfield{{Code: "a", Label: "Textual holdings", Repeatable: false}, {Code: "z", Label: "Public note", Repeatable: true}},
	},
	{
		Tag:        "876",
		Label:      "Item Information–Basic Bibliographic Unit",
		Definition: "Item-level information for a copy of the basic bibliographic unit.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "877",
		Label:      "Item Information–Supplementary Material",
		Definition: "Item-level information for a copy of supplementary material.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "878",
		Label:      "Item Information–Indexes",
		Definition: "Item-level information for a copy of an index.",
		Repeatable: true,
		Common:     false,
	},
	{
		Tag:        "882",
		Label:      "Replacement Record Information",
		Definition: "Information about the record that replaced this record.",
		Repeatable: false,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Replacement title", Repeatable: true},
			{Code: "i", Label: "Explanatory text", Repeatable: true},
			{Code: "w", Label: "Replacement bibliographic record control number", Repeatable: true},
			sfLink, sfFieldLink,
		},
	},
	{
		Tag:        "883",
		Label:      "Machine-generated Metadata Provenance",
		Definition: "Information about the provenance of automatically generated metadata.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Method employed", Repeatable: false},
			{Code: "c", Label: "Confidence value", Repeatable: false},
			{Code: "d", Label: "Generation date", Repeatable: false},
			{Code: "q", Label: "Generation agency", Repeatable: false},
			{Code: "u", Label: "Uniform Resource Identifier", Repeatable: false},
			{Code: "w", Label: "Bibliographic record control number", Repeatable: true},
			{Code: "x", Label: "Validity date range", Repeatable: false},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			sfFieldLink,
		},
	},
	{
		Tag:        "884",
		Label:      "Description Conversion Information",
		Definition: "Information about the conversion of the description from one metadata standard to MARC21.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Conversion process", Repeatable: false},
			{Code: "g", Label: "Conversion date", Repeatable: false},
			{Code: "k", Label: "Identifier of source metadata", Repeatable: false},
			{Code: "q", Label: "Conversion agency", Repeatable: false},
			{Code: "u", Label: "Uniform Resource Identifier", Repeatable: true},
		},
	},
	{
		Tag:        "885",
		Label:      "Matching Information",
		Definition: "Information about the matching of a record.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Matching information", Repeatable: false},
			{Code: "b", Label: "Agency that assigned value", Repeatable: false},
			{Code: "c", Label: "Creation/modification date", Repeatable: false},
			{Code: "d", Label: "Identifier", Repeatable: false},
			{Code: "w", Label: "Record control number", Repeatable: true},
			{Code: "x", Label: "Nonpublic note", Repeatable: true},
			{Code: "z", Label: "Public note", Repeatable: true},
			{Code: "0", Label: "Authority record control number or standard number", Repeatable: true},
			{Code: "2", Label: "Source", Repeatable: false},
			sfFieldLink,
		},
	},
	{
		Tag:        "886",
		Label:      "Foreign MARC Information Field",
		Definition: "Information from a foreign MARC record that cannot be mapped to another MARC field.",
		Repeatable: true,
		Common:     false,
		Indicators: [2]Indicator{
			{Label: "Type of field", Values: map[string]string{"0": "Leader", "1": "Variable control field", "2": "Variable data field"}},
			{Label: "Second indicator", Values: map[string]string{"#": "Undefined"}},
		},
		Subfields: []Subfield{
			{Code: "a", Label: "Tag of the foreign MARC field", Repeatable: false},
			{Code: "b", Label: "Content of the foreign MARC field", Repeatable: false},
			{Code: "2", Label: "Source of data", Repeatable: false},
			sfFieldLink,
		},
	},
	{
		Tag:        "887",
		Label:      "Non-MARC Information Field",
		Definition: "Any information that cannot be mapped to a MARC 21 field, stored in a non-MARC schema.",
		Repeatable: true,
		Common:     false,
		Subfields: []Subfield{
			{Code: "a", Label: "Content of non-MARC field", Repeatable: false},
			{Code: "2", Label: "Source of data", Repeatable: false},
		},
	},
}
