package schema

// field008Defs describes the MARC 008 Fixed-Length Data Elements field broken
// down by material type.
//
// Source: https://www.loc.gov/marc/bibliographic/bd008.html
var field008Defs = Field008Defs{
	Common: field008Common,
	ByType: map[string][]Field008Pos{
		"Books":           field008Books,
		"Serials":         field008Serials,
		"Maps":            field008Maps,
		"Music":           field008Music,
		"VisualMaterials": field008VisualMaterials,
		"ComputerFiles":   field008ComputerFiles,
		"MixedMaterials":  field008MixedMaterials,
	},
}

// field008Common covers positions 00-05 and 35-39 which are identical across
// all material types.
var field008Common = []Field008Pos{
	{
		Position:   "00-05",
		Label:      "Date entered on file",
		Definition: "Six-character numeric string that indicates the date the record was entered in a file or catalog. Format: YYMMDD.",
	},
	{
		Position:   "06",
		Label:      "Type of date/Publication status",
		Definition: "A one-character code that indicates the type of dates given in 008/07-10 (Date 1) and 008/11-14 (Date 2), and the publication status of the item.",
		Values: map[string]string{
			"b": "No dates given; B.C. date involved",
			"c": "Continuing resource currently published",
			"d": "Continuing resource ceased publication",
			"e": "Detailed date",
			"i": "Inclusive dates of collection",
			"k": "Range of years of bulk of collection",
			"m": "Multiple dates",
			"n": "Dates unknown",
			"p": "Date of distribution/release/issue and production/recording session when different",
			"q": "Questionable date",
			"r": "Reprint/reissue date and original date",
			"s": "Single known date of publication",
			"t": "Publication date and copyright date",
			"u": "Continuing resource status unknown",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "07-10",
		Label:      "Date 1",
		Definition: "Date 1 is a four-character number. Its meaning depends on the code in 008/06 (Type of date/Publication status). For single-date items it is the year of publication; for reprints the date of reissue; for serials the beginning year.",
	},
	{
		Position:   "11-14",
		Label:      "Date 2",
		Definition: "Date 2 is a four-character number. Its meaning depends on 008/06. For items with multiple dates it is the ending date; for reprints the original date; for uncertain dates a closing estimate. Blanks fill unused positions.",
	},
	{
		Position:   "15-17",
		Label:      "Place of publication, production, or execution",
		Definition: "A two- or three-character MARC code for the country of publication, production, or execution of the item. Source: MARC Code List for Countries.",
	},
	{
		Position:   "35-37",
		Label:      "Language",
		Definition: "A three-character MARC code that indicates the language of the item. Source: MARC Code List for Languages.",
	},
	{
		Position:   "38",
		Label:      "Modified record",
		Definition: "A one-character code that indicates whether any data in a bibliographic record is a modification of information that appeared on the item being cataloged or that was established in another authoritative source.",
		Values: map[string]string{
			"#": "Not modified",
			"d": "Dashed-on information omitted",
			"o": "Completely romanized/printed cards romanized",
			"r": "Completely romanized/printed cards in script",
			"s": "Shortened",
			"x": "Missing characters",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "39",
		Label:      "Cataloging source",
		Definition: "A one-character code that indicates the original cataloging source of the record. If the cataloging source is known, the appropriate code is given.",
		Values: map[string]string{
			"#": "National bibliographic agency",
			"c": "Cooperative cataloging program",
			"d": "Other",
			"u": "Unknown",
			"|": "No attempt to code",
		},
	},
}

// field008Books covers positions 18-34 for Books material type.
// Used when: Leader/06 = a or t AND Leader/07 = a, c, d, or m
var field008Books = []Field008Pos{
	{
		Position:   "18-21",
		Label:      "Illustrations",
		Definition: "Up to four one-character codes (positions 18, 19, 20, 21) indicate the character of illustrations in the item. A blank means no illustrations.",
		Values: map[string]string{
			"#": "No illustrations",
			"a": "Illustrations",
			"b": "Maps",
			"c": "Portraits",
			"d": "Charts",
			"e": "Plans",
			"f": "Plates",
			"g": "Music",
			"h": "Facsimiles",
			"i": "Coats of arms",
			"j": "Genealogical tables",
			"k": "Forms",
			"l": "Samples",
			"m": "Phonodisc, phonowire, etc.",
			"o": "Photographs",
			"p": "Illuminations",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "22",
		Label:      "Target audience",
		Definition: "A one-character code that indicates the intellectual level of the target audience for the item.",
		Values: map[string]string{
			"#": "Unknown or not specified",
			"a": "Preschool",
			"b": "Primary",
			"c": "Pre-adolescent",
			"d": "Adolescent",
			"e": "Adult",
			"f": "Specialized",
			"g": "General",
			"j": "Juvenile",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "23",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of material for the item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"e": "Newspaper format",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"r": "Regular print reproduction",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "24-27",
		Label:      "Nature of contents",
		Definition: "Up to four one-character codes (positions 24, 25, 26, 27) that indicate special types of information or material that may be of particular value to the user. A blank means no specified nature of contents.",
		Values: map[string]string{
			"#": "No specified nature of contents",
			"a": "Abstracts/summaries",
			"b": "Bibliographies",
			"c": "Catalogs",
			"d": "Dictionaries",
			"e": "Encyclopedias",
			"f": "Handbooks",
			"g": "Legal articles",
			"i": "Indexes",
			"j": "Patent document",
			"k": "Discographies",
			"l": "Legislation",
			"m": "Theses",
			"n": "Surveys of literature in a subject area",
			"o": "Reviews",
			"p": "Programmed texts",
			"q": "Filmographies",
			"r": "Directories",
			"s": "Statistics",
			"t": "Technical reports",
			"u": "Standards/specifications",
			"v": "Legal cases and case notes",
			"w": "Law reports and digests",
			"x": "Other reports",
			"y": "Yearbooks",
			"z": "Treaties",
			"2": "Offprints",
			"5": "Calendars",
			"6": "Comics/graphic novels",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "28",
		Label:      "Government publication",
		Definition: "A one-character code that indicates whether the item is published or produced by or for a government agency and at what level.",
		Values: map[string]string{
			"#": "Not a government publication",
			"a": "Autonomous or semi-autonomous body",
			"c": "Multilocal",
			"f": "Federal/national",
			"i": "International intergovernmental",
			"l": "Local",
			"m": "Multistate",
			"o": "Government publication — level undetermined",
			"s": "State, provincial, territorial, dependent, etc.",
			"u": "Unknown if item is government publication",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "29",
		Label:      "Conference publication",
		Definition: "A one-character code that indicates whether the item is a conference publication.",
		Values: map[string]string{
			"0": "Not a conference publication",
			"1": "Conference publication",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30",
		Label:      "Festschrift",
		Definition: "A one-character code that indicates whether the item is a festschrift.",
		Values: map[string]string{
			"0": "Not a festschrift",
			"1": "Festschrift",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "31",
		Label:      "Index",
		Definition: "A one-character code that indicates whether the item includes an index to its own contents.",
		Values: map[string]string{
			"0": "No index",
			"1": "Index present",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "32",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "33",
		Label:      "Literary form",
		Definition: "A one-character code that indicates whether the item is a work of fiction or nonfiction, and if fiction, the type of fiction.",
		Values: map[string]string{
			"0": "Not fiction (not further specified)",
			"1": "Fiction (not further specified)",
			"d": "Dramas",
			"e": "Essays",
			"f": "Novels",
			"h": "Humor, satire, etc.",
			"i": "Letters",
			"j": "Short stories",
			"m": "Mixed forms",
			"p": "Poetry",
			"s": "Speeches",
			"u": "Unknown",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "34",
		Label:      "Biography",
		Definition: "A one-character code that indicates whether the content of the item contains biographical information.",
		Values: map[string]string{
			"#": "No biographical information",
			"a": "Autobiography",
			"b": "Individual biography",
			"c": "Collective biography",
			"d": "Contains biographical information",
			"|": "No attempt to code",
		},
	},
}

// field008Serials covers positions 18-34 for Serials.
// Used when: Leader/06 = a AND Leader/07 = b, i, or s
var field008Serials = []Field008Pos{
	{
		Position:   "18",
		Label:      "Frequency",
		Definition: "A one-character code that indicates the frequency of publication of the item.",
		Values: map[string]string{
			"#": "No determinable frequency",
			"a": "Annual",
			"b": "Bimonthly",
			"c": "Semiweekly",
			"d": "Daily",
			"e": "Biweekly",
			"f": "Semiannual",
			"g": "Biennial",
			"h": "Triennial",
			"i": "Three times a week",
			"j": "Three times a month",
			"k": "Continuously updated",
			"m": "Monthly",
			"q": "Quarterly",
			"s": "Semimonthly",
			"t": "Three times a year",
			"u": "Unknown",
			"w": "Weekly",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "19",
		Label:      "Regularity",
		Definition: "A one-character code that indicates the intended regularity of an item.",
		Values: map[string]string{
			"n": "Normalized irregular",
			"r": "Regular",
			"u": "Unknown",
			"x": "Completely irregular",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "20",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "21",
		Label:      "Type of continuing resource",
		Definition: "A one-character code that indicates the type of continuing resource.",
		Values: map[string]string{
			"#": "None of the below",
			"d": "Updating database",
			"l": "Updating loose-leaf",
			"m": "Monographic series",
			"n": "Newspaper",
			"p": "Periodical",
			"w": "Updating Web site",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "22",
		Label:      "Target audience",
		Definition: "A one-character code that indicates the intellectual level of the target audience.",
		Values: map[string]string{
			"#": "Unknown or not specified",
			"a": "Preschool",
			"b": "Primary",
			"c": "Pre-adolescent",
			"d": "Adolescent",
			"e": "Adult",
			"f": "Specialized",
			"g": "General",
			"j": "Juvenile",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "23",
		Label:      "Form of original item",
		Definition: "A one-character code that indicates the form of material of the original item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"e": "Newspaper format",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "24",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of material for the item as published.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"r": "Regular print reproduction",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "25",
		Label:      "Nature of entire work",
		Definition: "A one-character code that indicates the nature of the entire serial publication.",
		Values: map[string]string{
			"#": "Not specified",
			"a": "Abstracts/summaries",
			"b": "Bibliographies",
			"c": "Catalogs",
			"d": "Dictionaries",
			"e": "Encyclopedias",
			"f": "Handbooks",
			"g": "Legal articles",
			"i": "Indexes",
			"k": "Discographies",
			"l": "Legislation",
			"m": "Theses",
			"n": "Surveys of literature in a subject area",
			"o": "Reviews",
			"p": "Programmed texts",
			"q": "Filmographies",
			"r": "Directories",
			"s": "Statistics",
			"t": "Technical reports",
			"u": "Standards/specifications",
			"v": "Legal cases and case notes",
			"w": "Law reports and digests",
			"x": "Other reports",
			"y": "Yearbooks",
			"z": "Treaties",
			"5": "Calendars",
			"6": "Comics/graphic novels",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "26-27",
		Label:      "Nature of contents",
		Definition: "Up to two one-character codes (positions 26 and 27) indicating special supplementary types of information or material.",
		Values: map[string]string{
			"#": "Not specified",
			"a": "Abstracts/summaries",
			"b": "Bibliographies",
			"c": "Catalogs",
			"i": "Indexes",
			"r": "Directories",
			"s": "Statistics",
			"t": "Technical reports",
		},
	},
	{
		Position:   "28",
		Label:      "Government publication",
		Definition: "A one-character code that indicates whether the item is published or produced by or for a government agency.",
		Values: map[string]string{
			"#": "Not a government publication",
			"a": "Autonomous or semi-autonomous body",
			"c": "Multilocal",
			"f": "Federal/national",
			"i": "International intergovernmental",
			"l": "Local",
			"m": "Multistate",
			"o": "Government publication — level undetermined",
			"s": "State, provincial, territorial, dependent, etc.",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "29",
		Label:      "Conference publication",
		Definition: "A one-character code that indicates whether the item is a conference publication.",
		Values: map[string]string{
			"0": "Not a conference publication",
			"1": "Conference publication",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30-32",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "33",
		Label:      "Original alphabet or script of title",
		Definition: "A one-character code that indicates the original alphabet or script of the language of the title on the source item.",
		Values: map[string]string{
			"#": "No alphabet or script given/No key title",
			"a": "Basic Roman",
			"b": "Extended Roman",
			"c": "Cyrillic",
			"d": "Japanese",
			"e": "Chinese",
			"f": "Arabic",
			"g": "Greek",
			"h": "Hebrew",
			"i": "Thai",
			"j": "Devanagari",
			"k": "Korean",
			"l": "Tamil",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "34",
		Label:      "Entry convention",
		Definition: "A one-character code that indicates the entry convention used in formulating the key title (field 222).",
		Values: map[string]string{
			"0": "Successive entry",
			"1": "Latest entry",
			"2": "Integrated entry",
			"|": "No attempt to code",
		},
	},
}

// field008Maps covers positions 18-34 for Maps.
// Used when: Leader/06 = e or f
var field008Maps = []Field008Pos{
	{
		Position:   "18-21",
		Label:      "Relief",
		Definition: "Up to four one-character codes that indicate the relief type shown on the map.",
		Values: map[string]string{
			"#": "No relief shown",
			"a": "Contours",
			"b": "Shading",
			"c": "Gradient and bathymetric tints",
			"d": "Hachures",
			"e": "Bathymetry/soundings",
			"f": "Form lines",
			"g": "Spot heights",
			"i": "Pictorially",
			"j": "Land forms",
			"k": "Bathymetry/isobaths",
			"m": "Rock drawings",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "22-23",
		Label:      "Projection",
		Definition: "A two-character code that indicates the projection used in producing the map.",
	},
	{
		Position:   "24",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "25",
		Label:      "Type of cartographic material",
		Definition: "A one-character code that indicates the type of cartographic item being described.",
		Values: map[string]string{
			"a": "Single map",
			"b": "Map series",
			"c": "Map serial",
			"d": "Globe",
			"e": "Atlas",
			"f": "Separate supplement to another work",
			"g": "Bound as part of another work",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "26-27",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
	{
		Position:   "28",
		Label:      "Government publication",
		Definition: "A one-character code that indicates whether the item is published by a government agency.",
		Values: map[string]string{
			"#": "Not a government publication",
			"a": "Autonomous or semi-autonomous body",
			"c": "Multilocal",
			"f": "Federal/national",
			"i": "International intergovernmental",
			"l": "Local",
			"m": "Multistate",
			"o": "Government publication — level undetermined",
			"s": "State, provincial, territorial, dependent, etc.",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "29",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of the map item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"r": "Regular print reproduction",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "31",
		Label:      "Index",
		Definition: "A one-character code that indicates whether the item includes an index.",
		Values: map[string]string{
			"0": "No index",
			"1": "Index present",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "32",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "33-34",
		Label:      "Special format characteristics",
		Definition: "Up to two one-character codes (positions 33 and 34) that indicate special format characteristics of the map.",
		Values: map[string]string{
			"#": "No specified special format characteristics",
			"e": "Manuscript",
			"j": "Picture card, post card",
			"k": "Calendar",
			"l": "Puzzle",
			"n": "Game",
			"o": "Wall map",
			"p": "Playing cards",
			"r": "Loose-leaf",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
}

// field008Music covers positions 18-34 for Music.
// Used when: Leader/06 = c, d, i, or j
var field008Music = []Field008Pos{
	{
		Position:   "18-19",
		Label:      "Composition",
		Definition: "A two-character code that indicates the form of composition represented in the item.",
		Values: map[string]string{
			"an": "Anthems",
			"bd": "Ballads",
			"bg": "Bluegrass music",
			"bl": "Blues",
			"bt": "Ballets",
			"ca": "Chaconnes",
			"cb": "Chants, Other religions",
			"cc": "Chant, Christian",
			"cg": "Concerti grossi",
			"ch": "Chorales",
			"cl": "Chorale preludes",
			"cn": "Canons and rounds",
			"co": "Concertos",
			"cp": "Chansons, polyphonic",
			"cr": "Carols",
			"cs": "Chance compositions",
			"ct": "Cantatas",
			"cy": "Country music",
			"cz": "Canzonas",
			"df": "Dance forms",
			"dv": "Divertimenti, serenades, cassations, divertissements, notturni",
			"fg": "Fugues",
			"fl": "Flamenco",
			"fm": "Folk music",
			"ft": "Fantasias",
			"gm": "Gospel music",
			"hy": "Hymns",
			"jz": "Jazz",
			"mc": "Musical revues and comedies",
			"md": "Madrigals",
			"mi": "Minuets",
			"mo": "Motets",
			"mp": "Motion picture music",
			"mr": "Marches",
			"ms": "Masses",
			"mu": "Multiple forms",
			"mz": "Mazurkas",
			"nc": "Nocturnes",
			"nn": "Not applicable",
			"op": "Operas",
			"or": "Oratorios",
			"ov": "Overtures",
			"pg": "Program music",
			"pm": "Passion music",
			"po": "Polonaises",
			"pp": "Popular music",
			"pr": "Preludes",
			"ps": "Passacaglias",
			"pt": "Part-songs",
			"pv": "Pavans",
			"rd": "Rondos",
			"rg": "Ragtime music",
			"ri": "Ricercars",
			"rp": "Rhapsodies",
			"rq": "Requiems",
			"sd": "Square dance music",
			"sg": "Songs",
			"sn": "Sonatas",
			"sp": "Symphonic poems",
			"st": "Studies and exercises",
			"su": "Suites",
			"sy": "Symphonies",
			"tc": "Toccatas",
			"tl": "Teatro lirico",
			"ts": "Trio-sonatas",
			"uu": "Unknown",
			"vi": "Villancicos",
			"vr": "Variations",
			"wz": "Waltzes",
			"za": "Zarzuelas",
			"zz": "Other",
		},
	},
	{
		Position:   "20",
		Label:      "Format of music",
		Definition: "A one-character code that indicates the format of the printed or manuscript music.",
		Values: map[string]string{
			"#": "Not specified or not applicable",
			"a": "Full score",
			"b": "Full score, miniature or study size",
			"c": "Accompaniment reduced for keyboard",
			"d": "Voice score",
			"e": "Condensed score or piano-conductor score",
			"g": "Close score",
			"h": "Chorus score",
			"i": "Condensed score",
			"j": "Performer-conductor part",
			"k": "Vocal score",
			"l": "Score",
			"m": "Multiple score formats",
			"n": "Not applicable",
			"p": "Piano score",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "21",
		Label:      "Music parts",
		Definition: "A one-character code that indicates whether the item being cataloged is, or contains, parts.",
		Values: map[string]string{
			"#": "No parts in item or not specified",
			"d": "Instrumental and vocal parts",
			"e": "Instrumental parts",
			"f": "Vocal parts",
			"n": "Not applicable",
			"u": "Unknown",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "22",
		Label:      "Target audience",
		Definition: "A one-character code that indicates the intellectual level of the target audience.",
		Values: map[string]string{
			"#": "Unknown or not specified",
			"a": "Preschool",
			"b": "Primary",
			"c": "Pre-adolescent",
			"d": "Adolescent",
			"e": "Adult",
			"f": "Specialized",
			"g": "General",
			"j": "Juvenile",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "23",
		Label:      "Form of composition",
		Definition: "A one-character code that indicates the form of material for the item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "24-29",
		Label:      "Accompanying matter",
		Definition: "Up to six one-character codes (positions 24 through 29) that indicate the contents of program notes and other material accompanying the sound recording.",
		Values: map[string]string{
			"#": "No accompanying matter",
			"a": "Discography",
			"b": "Bibliography",
			"c": "Thematic index",
			"d": "Libretto or text",
			"e": "Biography of composer or author",
			"f": "Biography of performer or history of ensemble",
			"g": "Technical and/or historical information on instruments",
			"h": "Technical information on music",
			"i": "Historical information",
			"k": "Ethnological information",
			"r": "Instructional materials",
			"s": "Music",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30-31",
		Label:      "Literary text for sound recordings",
		Definition: "For non-music sound recordings, one-character codes indicating the type of literary text.",
		Values: map[string]string{
			"#": "Item is a music sound recording",
			"a": "Autobiography",
			"b": "Biography",
			"c": "Conference proceedings",
			"d": "Drama",
			"e": "Essays",
			"f": "Fiction",
			"g": "Reporting",
			"h": "History",
			"i": "Instruction",
			"j": "Language instruction",
			"k": "Comedy",
			"l": "Lectures, speeches",
			"m": "Memoirs",
			"n": "Not applicable",
			"o": "Folktales",
			"p": "Poetry",
			"r": "Rehearsals",
			"s": "Sounds",
			"t": "Interviews",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "32",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "33",
		Label:      "Transposition and arrangement",
		Definition: "A one-character code that indicates whether the item is a transposition or arrangement.",
		Values: map[string]string{
			"#": "Not arrangement or transposition or not specified",
			"a": "Transposition",
			"b": "Arrangement",
			"c": "Both transposed and arranged",
			"n": "Not applicable",
			"u": "Unknown",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "34",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
}

// field008VisualMaterials covers positions 18-34 for Visual Materials.
// Used when: Leader/06 = g, k, o, or r
var field008VisualMaterials = []Field008Pos{
	{
		Position:   "18-20",
		Label:      "Running time for motion pictures and videorecordings",
		Definition: "Three-character numeric string giving the playing time of the motion picture or videorecording. '---' if not applicable, '000' if unknown, '999' if 999 min or longer.",
	},
	{
		Position:   "21",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "22",
		Label:      "Target audience",
		Definition: "A one-character code that indicates the intended audience.",
		Values: map[string]string{
			"#": "Unknown or not specified",
			"a": "Preschool",
			"b": "Primary",
			"c": "Pre-adolescent",
			"d": "Adolescent",
			"e": "Adult",
			"f": "Specialized",
			"g": "General",
			"j": "Juvenile",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "23-27",
		Label:      "Accompanying matter",
		Definition: "Up to five one-character codes indicating accompanying material.",
	},
	{
		Position:   "28",
		Label:      "Government publication",
		Definition: "A one-character code indicating government publication status.",
		Values: map[string]string{
			"#": "Not a government publication",
			"a": "Autonomous or semi-autonomous body",
			"c": "Multilocal",
			"f": "Federal/national",
			"l": "Local",
			"s": "State/provincial/territorial/dependent, etc.",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "29",
		Label:      "Form of item",
		Definition: "A one-character code indicating the form of material.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30-32",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
	{
		Position:   "33",
		Label:      "Type of visual material",
		Definition: "A one-character code that indicates the type of visual material being described.",
		Values: map[string]string{
			"a": "Art original",
			"b": "Kit",
			"c": "Art reproduction",
			"d": "Diorama",
			"f": "Filmstrip",
			"g": "Game",
			"i": "Picture",
			"k": "Graphic",
			"l": "Technical drawing",
			"m": "Motion picture",
			"n": "Chart",
			"o": "Flash card",
			"p": "Microscope slide",
			"q": "Model",
			"r": "Realia",
			"s": "Slide",
			"t": "Transparency",
			"v": "Videorecording",
			"w": "Toy",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "34",
		Label:      "Technique",
		Definition: "A one-character code that indicates the technique used in the production of motion pictures or videorecordings.",
		Values: map[string]string{
			"a": "Animation",
			"c": "Animation and live action",
			"l": "Live action",
			"n": "Not applicable",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
}

// field008ComputerFiles covers positions 18-34 for Computer Files.
// Used when: Leader/06 = m
var field008ComputerFiles = []Field008Pos{
	{
		Position:   "18-21",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
	{
		Position:   "22",
		Label:      "Target audience",
		Definition: "A one-character code that indicates the intellectual level of the target audience.",
		Values: map[string]string{
			"#": "Unknown or not specified",
			"a": "Preschool",
			"b": "Primary",
			"c": "Pre-adolescent",
			"d": "Adolescent",
			"e": "Adult",
			"f": "Specialized",
			"g": "General",
			"j": "Juvenile",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "23",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of material for the item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "24",
		Label:      "Undefined",
		Definition: "Undefined. Contains a blank or fill character.",
	},
	{
		Position:   "25",
		Label:      "Type of computer file",
		Definition: "A one-character code that indicates the type of computer file.",
		Values: map[string]string{
			"a": "Numeric data",
			"b": "Computer program",
			"c": "Representational",
			"d": "Document",
			"e": "Bibliographic data",
			"f": "Font",
			"g": "Game",
			"h": "Sound",
			"i": "Interactive multimedia",
			"j": "Online system or service",
			"m": "Combination",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "26-27",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
	{
		Position:   "28",
		Label:      "Government publication",
		Definition: "A one-character code that indicates whether the item is published by a government agency.",
		Values: map[string]string{
			"#": "Not a government publication",
			"a": "Autonomous or semi-autonomous body",
			"c": "Multilocal",
			"f": "Federal/national",
			"i": "International intergovernmental",
			"l": "Local",
			"m": "Multistate",
			"o": "Government publication — level undetermined",
			"s": "State, provincial, territorial, dependent, etc.",
			"u": "Unknown",
			"z": "Other",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "29",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of material for the item.",
		Values: map[string]string{
			"#": "None of the below",
			"o": "Online",
			"q": "Direct electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "30-34",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
}

// field008MixedMaterials covers positions 18-34 for Mixed Materials.
// Used when: Leader/06 = p
var field008MixedMaterials = []Field008Pos{
	{
		Position:   "18-22",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
	{
		Position:   "23",
		Label:      "Form of item",
		Definition: "A one-character code that indicates the form of the item.",
		Values: map[string]string{
			"#": "None of the below",
			"a": "Microfilm",
			"b": "Microfiche",
			"c": "Microopaque",
			"d": "Large print",
			"f": "Braille",
			"o": "Online",
			"q": "Direct electronic",
			"s": "Electronic",
			"|": "No attempt to code",
		},
	},
	{
		Position:   "24-34",
		Label:      "Undefined",
		Definition: "Undefined. Contains blanks or fill characters.",
	},
}
